Rtps gen pr
eProsima/Firmware pull request #8
Opened 2017-06-09 21:03 UTC by edersondisouza

Hi,

This PR comprises some changes that I believe to be important for generated code. Basically:
  - Define a uniform header so send CDR serialised messages over UART. 
  - Make `rx_buffer` internal to `UART_node`
  - Use a dedicated thread to read from UART.
  - Stop polling on uORB topics - since we sleep on this loop, so it should be cheaper checking all topics status. The same is done on mavlink module
  - Poll on UART to read from it. This allows usage of protocol splitter driver.

This PR also contains 3 more commits related to protocol splitter driver. I thought of sending them on a separated PR to PX4/Firmware, but it didn't make much sense to me, since there's nothing related to RTPS there yet. Sending here so it can be carried together when RTPS becomes upstream.

Changes are mainly on 'PX4/rtps_client' side. Changes to 'rtps_agent' are only to keep them compatible. I have some work to split mavlink/rtps on UART on companion computer, but I don't think it's worth here, since this scenario looks Intel Aero specific.

Please review: I tried to keep all changes small, and I'm not sure of all of them. For instance, 
I wonder if 'UART_node: make init_uart return UART file descriptor' could be changed to simply expose its internal file descriptor. Last one, 'rtps client: Use getopt to parse command line args' can be superfluous. And even though I've tested them here, maybe some changes break on other scenarios, so please, test too =D

Finally, my branch https://github.com/edersondisouza/Firmware/commits/rtps-gen has some extra commit with changes to allow a test program to be run, as well as the `rtps_router` application (for some messages only).

2017-06-14 16:44 UTC, edersondisouza commented
Just a note: I've updated 'UART_node: make init_uart return UART file descriptor' to also change `microRTPS_agent.cxx.template` code, that was oversight on first patch.

2017-06-14 18:56 UTC, vicentemonge requested changes
Hi Ederson, first at all thanks for the effort. The code looks great. I reviewed the code and I made some test over the PR without using the protocol splitter yet. As result I introduced some changes:

- Deleted unused parameter 'buff_total_len' in readFromUART
- Inside readFromUART I changed some about searching of 'msg_start_pos' to simplify.
- I added a 8 bit field to the header to make possible send messages greater than 255 bytes.
- I correct a mistake in 'writeToUART' over the checking of a returned value.

I included these changes in the branch rtps-gen-pr-changes. Please, take a look and tell me what you think.

2017-06-16 11:26 UTC, VicenteEprosima commented
I'm encountered some problems in the behavior of the micrortps_client running in a single core PIXracer with the scheduling of the threads, taking most time the main thread and letting without enough time to the read thread. I have tried to set differents priorities to the thread but doesn't works. What only works for me is introduce a minimum sleep but this decrease the compute time and the general performance.

2017-06-16 15:55 UTC, edersondisouza commented
@VicenteEprosima That's interesting. I can (and probably will) drop this part of the patch. But this behaviour made me curious: wouldn't we be also starving other threads, especially low priority ones? Maybe we *must* have some sleeping - RTPS is not the only thing running here.
@bkueng any thoughs on this?
[I would also ask Villi, but no idea of his github username]

2017-06-19 11:37 UTC, bkueng commented
If you have `usleep(_options.usleep);` with 0, you will have a busy loop. This needs to be avoided. Also be aware that the `sleep` granularity under NuttX is only 1ms, you can look at how [logger](https://github.com/edersondisouza/Firmware/blob/c8f1f8c7b6b1286386d3c195bf2f1264da0fa8a2/src/modules/logger/logger.cpp#L1058) does it: it sleeps on a semaphore for more accurate scheduling.
Where did you change the priority? In this case the priority of `micrortps_client_main` needs to be reduced in the [CMakeLists.txt](https://github.com/edersondisouza/Firmware/blob/c8f1f8c7b6b1286386d3c195bf2f1264da0fa8a2/msg/templates/uorb/microRTPS_client_CMakeLists.txt.template#L35), for example like this: https://github.com/edersondisouza/Firmware/blob/c8f1f8c7b6b1286386d3c195bf2f1264da0fa8a2/src/modules/logger/CMakeLists.txt#L37. But the template will need to be changed to actually start a background task with `px4_task_spawn_cmd` (look at how logger does it), so that we can use `micrortps_client [start|stop|status]` etc, allowing to set the priority properly. This task would then create the reader thread the same way as it's currently done.

Including @vilhjalmur89

2017-06-21 05:39 UTC, edersondisouza commented
v2 on #9

2017-06-21 05:39 UTC, closed without merging